# Generated by Django 5.2.4 on 2025-07-23 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Title',
            new_name='title',
        ),
    ]
